# Generated by Django 4.0.1 on 2022-02-01 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('src', '0003_taskdate'),
    ]

    operations = [
        migrations.CreateModel(
            name='History',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('history', models.TextField(default='{}')),
            ],
        ),
    ]
